export const userRows = [
    { id: 1,
   username:"Mahame Snow", 
    avatar: "../Assets/images/alf1.jpeg",
    email:"mahame@gmail.com",
    status:"active",
    transaction:"$120.000",
 },
 { id: 2,
 username:"Uwase Snow", 
 avatar: "../Assets/images/alf1.jpeg",
 email:"uwase@gmail.com",
 status:"active",
 transaction:"$80.000",
},

{ id: 3,
username:"Alice Snow", 
avatar: "../Assets/images/alf1.jpeg",
email:"alice@gmail.com",
status:"active",
transaction:"$170.000",
},

{ id: 4, 
username:"Bernice Snow", 
avatar: "../Assets/images/alf1.jpeg",
email:"be@gmail.com",
status:"active",
transaction:"$20.000",
},

{ id: 5,
username:"Mutoni Snow", 
avatar: "../Assets/images/alf1.jpeg",
email:"mutonie@gmail.com",
status:"active",
transaction:"$60.000",
},

  ];
  